spring:
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtps
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    username: froznfox4@gmail.com
    password: passwordddd